# Site settings
title:       Alex Learns Programming
email:       alexmontjohn@gmail.com
author:      Alex Johnson
description: "I'm learning computer science (and math!) and writing about the process."
baseurl:     ""
url:         "http://code.alxmjo.com"
date_format: "%b %-d, %Y"
excerpt_separator: <!--more-->
face_image: /images/35271-2017-Jun-23-AMJ-X.jpg
non_face_image: /images/cs261notes.jpg

# Google services
google_analytics: UA-21369664-5
google_verification: 

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Twitter
twitter_username: alxmjo

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:title/
paginate:     5
future: false
show_drafts: false
sass:
  compressed: true

# Plugins
plugins:
  - jekyll-paginate